### ISSUE TITLE
FPSMeter is not defined

### ISSUE THREAD

**Issue by m-obeid** [fifomori/chromori#2]
I'm using OMORI v1.0.8 and Google Chrome and get this error. The Chrome console shows a lot of errors: https://pastebin.com/GTWzucuw

**Comment by cafeed28** [comment]
This can happen due to slow loading (sometimes I encountered such errors when testing on a mobile and running the server on a pc). Usually a simple page reload can fix this, but if it doesn't, please provide a screenshot of DevTools Network tab, sorted by descending Time column

**Comment by m-obeid** [comment]
![image](https://github.com/fifomori/chromori/assets/69859290/bc51b4f1-d892-45a0-bc3e-1956c3b5c5dc)

**Comment by cafeed28** [comment]
Looks like your config has incorrect key, show your config.json file

**Comment by m-obeid** [comment]
![image](https://github.com/fifomori/chromori/assets/69859290/7a6ec1c6-0235-44e7-b81c-682ba5b84a5a)
that doesnt look right

**Comment by cafeed28** [comment]
I guess the issue is that you have a space in the chromori path, a temporary fix is ​​to delete your config file and move chromori somewhere without spaces in the path.
Will fix it soon (hopefully)

**Comment by m-obeid** [comment]
i entered the key manually and now it works! this is awesome dude, thanks!

**Comment by cafeed28** [comment]
Good to hear, thank you😼. I think I found the real issue (`nwapp-path="C:\Users\Admin\Saved` is exactly same length as OMORI key), will fix it soon
