### ISSUE TITLE
static error

### ISSUE THREAD

**Issue by GrandDiJay** [fifomori/chromori#3]
![image](https://github.com/fifomori/chromori/assets/56603737/a8c63379-b2d4-49df-9952-7101a290177c)

**Comment by cafeed28** [comment]
looks like your omori is installed in a different directory than default, open `config.json` and change `gamePath` to your omori directory path (where omori.exe is located). make sure to use double backslash `\\` instead of single `\`

**Comment by cafeed28** [comment]
should be fixed in commit [a8675fe](https://github.com/fifomori/chromori/commit/a8675fe6059e3fd2c3f9581c4eaf155822260567)
